### ISSUE TITLE
Implement PaStreamCallbackTimeInfo for pulseaudio hostapi

### ISSUE THREAD

**Issue by ralph-irving** [illuusio/assembla-mirror-portaudio-pulseaudio#2]
Please add support for PaStreamCallbackTimeInfo to the pulseaudio hostapi.

**Comment by illuusio** [comment]
I have to dive into this and explain to myself how this differs from normal time returning.

**Comment by illuusio** [comment]
Ok now this should be implemented for playback and record

**Comment by ralph-irving** [comment]
Thank you again for all your work bringing the pulseaudio hostapi in line with the alsa implementation.  I've been successfully running the latest code in squeezelite for the last 2 days and as of today I have a pulseaudio squeezeplay implementation as well.  Will continue to test for the next while before closing the issue.

**Comment by illuusio** [comment]
Multiple thaks for testing and tolerating this slow iteration. I have to dig into #3 bug because I think it will solve multiple problems.

**Comment by illuusio** [comment]
Should this be closed?

**Comment by ralph-irving** [comment]
I haven't had a chance to test the TimeInfo changes yet.  I'll try to do that soon and report back.

**Comment by ralph-irving** [comment]
Thank you for adding the TimeInfo to pulseaudio.
