### ISSUE TITLE
Could you update this to mirror version? 

### ISSUE THREAD

**Issue by its-pointless** [illuusio/assembla-mirror-portaudio-pulseaudio#4]
Also i have a good use for this on android/termux. We can't use portaudio's android implementation since it uses java stuff. But this works since pulseaudio is working.

**Comment by illuusio** [comment]
I'll also reduce amount of needed patches when I update (rebase this top of current git) this so you'll have to update your repo hard way. Is it ok with you?

**Comment by its-pointless** [comment]
The patch is tiny its literally change the order of 2 lines of code.

**Comment by illuusio** [comment]
Ok small patch easy to review :dagger:

**Comment by illuusio** [comment]
Ok now it's updated and they should equal. Hopefully I can mirror it back to Assembla also.

**Comment by illuusio** [comment]
Ok this one is also to be closed
